# Generated by Django 4.1.2 on 2022-12-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.UUIDField(blank=True, default=None, null=True, unique=True)),
                ('fio', models.CharField(default='', max_length=255, verbose_name='ФИО')),
                ('car', models.CharField(default='Toyota', max_length=255, verbose_name='Марка машины')),
                ('car_model', models.CharField(default='Auris', max_length=255, verbose_name='Модель автомобиля')),
                ('phone_number', models.CharField(default='+375445905077', max_length=255, verbose_name='Номер телефона')),
                ('service', models.CharField(choices=[('am', 'Автомойка'), ('sm', 'Шиномонтаж'), ('re', 'Ремонт электрики'), ('kd', 'Компьютерная диагностика')], default='', max_length=255, verbose_name='Услуга')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
