# Generated by Django 4.1.2 on 2022-10-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('client_surname', models.CharField(max_length=50, verbose_name='Фамилия клиента')),
                ('client_middleName', models.CharField(max_length=50, verbose_name='Отчество клиента')),
                ('client_car', models.CharField(max_length=50, verbose_name='Автомобиль клиента')),
                ('client_carModel', models.CharField(max_length=50, verbose_name='Модель автомибиля клиента')),
                ('client_carYear', models.CharField(max_length=4, verbose_name='Год выпуска автомобиля')),
                ('pub_order', models.DateTimeField(verbose_name='Дата заказа')),
            ],
        ),
    ]
