# Generated by Django 4.1.2 on 2022-11-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('service_time_work', models.IntegerField(verbose_name='Примерное время работы')),
                ('service_employee', models.CharField(max_length=50, verbose_name='Фамилия работника')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'КЛИЕНТОВ', 'verbose_name_plural': 'Клиент'},
        ),
    ]
