# Generated by Django 4.1.2 on 2022-11-29 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_services_alter_article_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='service_employee',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_time_work',
        ),
        migrations.AddField(
            model_name='article',
            name='client_service',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='articles.services'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(default='', max_length=50, verbose_name='Название услуги'),
        ),
    ]
