# Generated by Django 4.1.2 on 2022-12-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_services_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='client_car',
        ),
        migrations.RemoveField(
            model_name='article',
            name='client_carModel',
        ),
        migrations.RemoveField(
            model_name='article',
            name='client_carYear',
        ),
        migrations.RemoveField(
            model_name='article',
            name='client_middleName',
        ),
        migrations.RemoveField(
            model_name='article',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='client_surname',
        ),
        migrations.AddField(
            model_name='article',
            name='car',
            field=models.CharField(default='Toyota', max_length=255, verbose_name='Марка машины'),
        ),
        migrations.AddField(
            model_name='article',
            name='car_model',
            field=models.CharField(default='Auris', max_length=255, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='article',
            name='fio',
            field=models.CharField(default='', max_length=255, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='article',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='article',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='phone_number',
            field=models.CharField(default='+375445905077', max_length=255, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='article',
            name='service',
            field=models.CharField(choices=[('am', 'Автомойка'), ('sm', 'Шиномонтаж'), ('re', 'Ремонт электрики'), ('kd', 'Компьютерная диагностика')], default='', max_length=255, verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='article',
            name='uid',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
