# Generated by Django 4.1.2 on 2022-12-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_client_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='uid',
        ),
        migrations.AlterField(
            model_name='article',
            name='fio',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='ФИО'),
        ),
    ]
