# Generated by Django 4.1.2 on 2022-12-05 08:20

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_article_uid_alter_article_fio'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
