# Generated by Django 4.1.2 on 2022-12-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='article',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='article',
            name='password',
        ),
        migrations.RemoveField(
            model_name='article',
            name='service',
        ),
    ]
