# Generated by Django 4.1.2 on 2022-12-05 08:50

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_managers_remove_article_fio_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='fio',
            field=models.CharField(default='', max_length=255, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='article',
            name='service',
            field=models.CharField(choices=[('am', 'Автомойка'), ('sm', 'Шиномонтаж'), ('re', 'Ремонт электрики'), ('kd', 'Компьютерная диагностика')], default='', max_length=255, verbose_name='Услуга'),
        ),
    ]
