# Generated by Django 4.1.2 on 2022-12-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_article_managers_article_fio_article_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='fio',
            field=models.CharField(default='Рубец Алексей Сергеевич', max_length=255, verbose_name='ФИО'),
        ),
    ]
