# Generated by Django 4.1.2 on 2022-12-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_fio'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='service',
        ),
    ]
