# Generated by Django 4.1.2 on 2022-12-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_managers_remove_article_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='client_service',
        ),
    ]
