# Generated by Django 4.1.2 on 2022-12-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_remove_article_client_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='pub_order',
        ),
        migrations.AlterField(
            model_name='article',
            name='car',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='car_model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='fio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
