# Generated by Django 4.1.2 on 2022-12-07 15:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_article_options_remove_article_pub_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='client_service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='articles.services'),
        ),
        migrations.AddField(
            model_name='article',
            name='pub_order',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 15, 34, 4, 241630, tzinfo=datetime.timezone.utc), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='article',
            name='car',
            field=models.CharField(default='Toyota', max_length=255, verbose_name='Марка машины'),
        ),
        migrations.AlterField(
            model_name='article',
            name='car_model',
            field=models.CharField(default='Auris', max_length=255, verbose_name='Модель автомобиля'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fio',
            field=models.CharField(default='Рубец Алексей Сергеевич', max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='article',
            name='phone_number',
            field=models.CharField(default='+375445905077', max_length=255, verbose_name='Номер телефона'),
        ),
    ]
