# Generated by Django 4.1.2 on 2022-12-07 15:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_article_client_service_article_pub_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='client_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.services'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_order',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 15, 34, 37, 76671, tzinfo=datetime.timezone.utc), verbose_name='Дата заказа'),
        ),
    ]
