# Generated by Django 4.1.2 on 2022-12-07 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_article_client_service_alter_article_pub_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_order',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 15, 36, 38, 207036, tzinfo=datetime.timezone.utc), verbose_name='Дата заказа'),
        ),
    ]
