# Generated by Django 4.1.2 on 2022-12-07 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_alter_article_pub_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_order',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 15, 38, 43, 41747, tzinfo=datetime.timezone.utc), verbose_name='Дата заказа'),
        ),
    ]
