# Generated by Django 4.1.2 on 2023-02-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_alter_article_pub_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='car_model',
        ),
        migrations.AlterField(
            model_name='article',
            name='car',
            field=models.CharField(choices=[('Toyota', (('C-HR', 'C-HR'), ('Sai', 'Sai'), ('Auris', 'Auris'), ('Prius', 'Prius'), ('Land Cruiser', 'Land Cruiser'), ('Avensis', 'Avensis'), ('Camry', 'Camry'), ('Highlander', 'Highlander'), ('RAV4', 'RAV4'), ('Crown', 'Crown')))], default='Не указан', max_length=15, verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fio',
            field=models.CharField(default='Рубец Алексей Сергеевич', max_length=30, verbose_name='ФИО'),
        ),
    ]
