# Generated by Django 4.1.2 on 2023-02-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_remove_article_car_model_alter_article_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='article',
            name='Номер телефона',
            field=models.CharField(default='+375445905077', help_text='Формат: (29/44/33) 1111 222', max_length=255, verbose_name='/\\(?([0-9]{3})\\)?([ .-]?)([0-9]{3})\\2([0-9]{4})/'),
        ),
    ]
