# Generated by Django 4.1.2 on 2023-02-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_remove_article_phone_number_article_номер телефона'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Номер телефона',
        ),
        migrations.AddField(
            model_name='article',
            name='phone_number',
            field=models.CharField(default='+375445905077', help_text='Формат: (29/44/33) 1111 222', max_length=255, verbose_name='Номер телефона'),
        ),
    ]
