# Generated by Django 4.1.2 on 2023-02-26 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_services_service_price_services_service_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_fio', models.CharField(default='Рубец Алексей Сергеевич', max_length=50, validators=[django.core.validators.RegexValidator('[А-ЯЁёA-Z][а-яёa-z]{2,25}\\s[А-ЯЁёA-Z][а-яёa-z]{2,25}\\s[А-ЯЁёA-Z][А-Яа-яЁёA-Za-z]{2,25}\\s?')], verbose_name='ФИО')),
                ('employee_age', models.IntegerField(default=18, help_text='Возраст работника', verbose_name='Возраст')),
                ('employee_phoneNumber', models.CharField(help_text="Телефонный номер должен быть в форме: '+375(17/25/29/33/44)XXXXXXX'.", max_length=20, validators=[django.core.validators.RegexValidator('\\+375(17|29|25|33|44)[0-9]{7}')], verbose_name='Телефонный номер')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='car',
            field=models.CharField(choices=[('Toyota', (('C-HR', 'C-HR'), ('Sai', 'Sai'), ('Auris', 'Auris'), ('Prius', 'Prius'), ('Land Cruiser', 'Land Cruiser'), ('Avensis', 'Avensis'), ('Camry', 'Camry'), ('Highlander', 'Highlander'), ('RAV4', 'RAV4'), ('Crown', 'Crown'))), ('Renault', (('Latitude', 'Latitude'), ('Koleos', 'Koleos'), ('Arkana', 'Arkana'), ('Kaptur', 'Kaptur'), ('Fluence', 'Fluence'), ('Grand Scenic', 'Grand Scenic'), ('Laguna', 'Laguna'), ('Trafic', 'Trafic'), ('Logan Stepway', 'Logan Stepway'), ('Duster', 'Duster'))), ('Opel', (('Insignia', 'Insignia'), ('Mokka', 'Mokka'), ('Astra GTC', 'Astra GTC'), ('Antara', 'Antara'), ('Astra Family', 'Astra Family'), ('Astra', 'Astra'), ('Zafira', 'Zafira'), ('Vivaro', 'Vivaro'), ('Corsa', 'Corsa'), ('Meriva', 'Meriva'))), ('Honda', (('Legend', 'Legend'), ('Shuttle', 'Shuttle'), ('N-WGN', 'N-WGN'), ('Crosstour', 'Crosstour'), ('Civic Type R', 'Civic Type R'), ('Vezel', 'Vezel'), ('CR-Z', 'CR-Z'), ('Jade', 'Jade'), ('Fit Shuttle', 'Fit Shuttle'), ('Freed Spike', 'Freed Spike'))), ('BMW', (('6-Series', '6-Series'), ('X6', 'X6'), ('X5', 'X5'), ('5-Series Gran Turismo', '5-Series Gran Turismo'), ('X4', 'X4'), ('X3', 'X3'), ('7-Series', '7-Series'), ('3-Series Gran Turismo', '3-Series Gran Turismo'), ('5-Series', '5-Series'), ('Z4', 'Z4'))), ('Mercedes-Benz', (('CLS-Class', 'CLS-Class'), ('GLA-Class', 'GLA-Class'), ('GL-Class', 'GL-Class'), ('GLE-Coupe', 'GLE-Coupe'), ('CL-Class', 'CL-Class'), ('GLE', 'GLE'), ('S-Class', 'S-Class'), ('GLK-CLASS', 'GLK-Class'), ('GLS-Class', 'GLS-Class'), ('CLK-Class', 'CLK-Class'))), ('Audi', (('A7', 'A7'), ('Q7', 'Q7'), ('A5', 'A5'), ('Q5', 'Q5'), ('Q3', 'Q3'), ('A1', 'A1'), ('TT', 'TT'), ('A3', 'A3'), ('A8', 'A8'), ('A6 Allroad Quattro', 'A6 Allroad Quattro'))), ('Geely', (('Coolray SX11', 'Coolray SX11'), ('Atlas', 'Atlas'), ('Emgrand EC7', 'Emgrand EC7'), ('Vision', 'Vision'), ('GC6', 'GC6'), ('MK Cross', 'MK Cross'), ('MK', 'MK'), ('Emgrand X7', 'Emgrand X7'), ('Otaka CK', 'Otaka CK'), ('CK', 'CK'))), ('Lada', (('Granta Sport', 'Granta Sport'), ('Vesta Cross', 'Vesta Cross'), ('Vesta', 'Vesta'), ('Kalina Cross', 'Kalina Cross'), ('X-Ray Cross', 'X-Ray Cross'), ('Kalina Sport', 'Kalina Sport'), ('Granta Cross', 'Granta Cross'), ('X-Ray', 'X-Ray'), ('Largus', 'Largus'), ('Largus Cross', 'Largus Cross'))), ('Volkswagen', (('Passat CC', 'Passat CC'), ('Touareg', 'Touareg'), ('Tiguan', 'Tiguan'), ('Phaeton', 'Phaeton'), ('Scirocco', 'Scirocco'), ('Amarok', 'Amarok'), ('Beetle', 'Beetle'), ('Jetta', 'Jetta'), ('Multivan', 'Multivan'), ('Touran', 'Touran'))), ('Lexus', (('LX570', 'LX570'), ('GS350', 'GS350'), ('IS250', 'RX450h'), ('ES250', 'ES250'), ('GS250', 'GS250'), ('LS430', 'LS430'), ('LS600hL', 'LS600hl'), ('NX200t', 'NX200t'), ('RX400h', 'RX400h'), ('RX350', 'RX350'))), ('Škoda', (('Superb', 'Superb'), ('Kodiaq', 'Kodiaq'), ('Rapid', 'Rapid'), ('Octavia', 'Octavia'), ('Karoq', 'Karoq'), ('Yeti', 'Yeti  '), ('Fabia', 'Fabia'), ('Roomster', 'Roomster'), ('Felicia', 'Felicia'))), ('Nissan', (('Leaf', 'Leaf'), ('Teana', 'Teana'), ('Terrano', 'Terrano'), ('Cima', 'Cima'), ('Silvia', 'Silvia'), ('Almera', 'Almera'), ('Murrano', 'Murrano'), ('Patrol', 'Patrol'), ('Sentra', 'Sentra'), ('X-Trail', 'X-Trail')))], default='Не указан', max_length=30, verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fio',
            field=models.CharField(default='Рубец Алексей Сергеевич', max_length=50, validators=[django.core.validators.RegexValidator('[А-ЯЁёA-Z][а-яёa-z]{2,25}\\s[А-ЯЁёA-Z][а-яёa-z]{2,25}\\s[А-ЯЁёA-Z][А-Яа-яЁёA-Za-z]{2,25}\\s?')], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_time',
            field=models.IntegerField(default=1, help_text='Время указано в минутах', verbose_name='Примерное время'),
        ),
    ]
