# Generated by Django 4.1.2 on 2023-02-26 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_rank',
            field=models.CharField(default='', max_length=25, validators=[django.core.validators.RegexValidator('\\w')], verbose_name='Должность'),
        ),
    ]
